### ISSUE TITLE
issue登録テスト

### ISSUE THREAD

**Issue by tsuboi-syskey** [tsuboi-syskey/sandbox_github#14]
### 見出しです

* リスト1
* リスト2

<strong>あああ</strong>
**ああ**

 @sand20160510 

> echo "aaa";

`echo` "aaa";

![octocat](https://cloud.githubusercontent.com/assets/19260903/15424448/9ae02230-1ebd-11e6-90d8-87f38f648ed9.png)

**Comment by sand20160510** [comment]
対応しました。closesします

**Comment by tsuboi-syskey** [comment]
#1
